### ISSUE TITLE
Serialize and deserialize

### ISSUE THREAD

**Issue by ethanabrooks** [vigoo/prox#115]
Is there a reliable way to convert a `Process[IO, _, _]` to a string and back?

**Comment by vigoo** [comment]
Not really as the attached input/output/error streams are also part of the process value.

**Comment by ethanabrooks** [comment]
Suppose I have a string and I want to execute it as if it were a bash script, in the current working directory. One option is to write it to a tempfile and execute it that way, but perhaps there is a better way?
