### ISSUE TITLE
Method for getting a process's PID

### ISSUE THREAD

**Issue by kubukoz** [vigoo/prox#146]
Hi!

It would be nice to be able to get the process's PID (e.g. to ask the system to print some information about the process), much like in Java's Process API.

I assume it might couple the API to the specifics of process running (e.g. if you wanted to have a remote process runner via ssh, it might not make much sense to just return the pid on the remote server), so maybe it could be part of a type that ProcessRunner would be parameterized with (possibly a type member, so you would only have to care if you wanted to use it).

Something like

```scala
trait ProcessRunner[F[_]]
  type Info
  def run(...): F[Process.Aux[F, Info]]
}
```

comes to mind.

**Comment by vigoo** [comment]
Hi! Thank's for the request, I like the idea. Will come up with something in the next days.
