### ISSUE TITLE
Update to cats-effect 3

### ISSUE THREAD

**Issue by kubukoz** [vigoo/prox#215]
Hi, is there any plan for migrating to cats-effect 3?

**Comment by vigoo** [comment]
Absolutely! I did not play with it yet, but I definitely want to support it.

**Comment by kubukoz** [comment]
Do you want to keep 2.x support on a separate branch? Or just going full in 3.0?

**Comment by vigoo** [comment]
As there is already an abstraction layer to support both CE+FS2 and ZIO+ZStream, I would expect that it's easy to have a CE2 and CE3 implementation in parallel and maintain both for a while, both part of the main branch. I have no idea if people are actually using this library :) But I know it is used at Prezi with CE2 so would not want to support that for a while.
