### ISSUE TITLE
Upgrade to Cats Effects 1.0.0 and FS2 1.0.0-RC2

### ISSUE THREAD

**Issue by denisrosset** [vigoo/prox#4]
Hi!
seems to be a wonderful library. I've tried to upgrade the dependencies to cats-effects 1.0.0, and FS2 1.0.0-RC2, and did not go very far.

In particular, `async.start` is gone, and calling `io.readInputStream` requires a `ContextShift` instance, and I don't know how to provide one.

Any ideas on how to perform the upgrade?

**Comment by vigoo** [comment]
Yes there were a lot of changes in these libraries in the past months :)
If you are interested, these two pages explains them pretty well:
- [Concurrency Basics at cats-effect](https://typelevel.org/cats-effect/concurrency/basics.html)
- [Migration guide for fs2](https://github.com/functional-streams-for-scala/fs2/blob/series/1.0/docs/migration-guide-1.0.md#fs2io-changes)

This pull request implements the upgrade: https://github.com/vigoo/prox/pull/5 
I'm going to merge and publish soon.

**Comment by vigoo** [comment]
Done
