### ISSUE TITLE
0.4 not on Maven Central?

### ISSUE THREAD

**Issue by kubukoz** [vigoo/prox#50]
Hi! I wanted to give the library a try, but I'm using fs2 2.x and prox's compatible release seems only to have been tagged but not released: http://repo1.maven.org/maven2/io/github/vigoo/prox_2.12/ only has versions up to 0.3 and there are no other releases of prox for other Scala versions. Would you mind publishing the jars?

**Comment by vigoo** [comment]
Hi! It was prepared on sonatype since 14th of September and I forgot to push the release button :o Now I did, it should be out very soon. Thanks for giving it a try!

**Comment by kubukoz** [comment]
Good to see that! I'll close this, then :)

**Comment by kubukoz** [comment]
Thanks!

**Comment by kubukoz** [comment]
Apparently 0.4 is only there for 2.13, but it includes an upgrade of fs2 (1.x -> 2.x is binary breaking), so it should also be released for 2.12... I'll reopen this until there's a release, if you don't mind :)

**Comment by kubukoz** [comment]
Ooops, it was just a stale cache. Sorry!
